# Bones
bones_boot = File.join(File.dirname(__FILE__), 'bones', 'boot.rb')

if File.file?(bones_boot)
  require bones_boot
else
  require 'rubygems'
  require 'bones'
end
  
Bones.root = File.expand_path('.')

require 'rake'
require 'tasks/bones'